[package]
disabled = true

[character]
use_symbol_for_status = true

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸ“¤"
behind = "ğŸ“¥"
diverged = "ğŸ”€"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“˜"
staged = "ğŸ“—"
renamed = "ğŸ“’"
deleted = "ğŸ“•"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[memory]
disabled = false

[kubernetes]
disabled = true
